name: 💾 Fetch || ⏫ Update NDK Package Formulas 📦
#MAX_RUNTIME: ~ 5-15 mins

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 Hrs

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: "main"
          filter: "blob:none"

      - name: Setup Env
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          ##Install coreutils
          sudo apt-get update -y -qq && sudo apt-get install curl coreutils dos2unix file findutils gawk git jq moreutils rsync tar xz-utils util-linux wget zip -y -qq
          ##Install Addons
          #ansi2txt
          sudo curl -qfsSL "https://bin.ajam.dev/$(uname -m)/ansi2txt" -o "/usr/local/bin/ansi2txt" && sudo chmod +x "/usr/local/bin/ansi2txt"
          #eget
          sudo curl -qfsSL "https://bin.ajam.dev/$(uname -m)/eget" -o "/usr/local/bin/eget" && sudo chmod +x "/usr/local/bin/eget"
          #jq
          sudo curl -qfsSL "https://bin.ajam.dev/$(uname -m)/jq" -o "/usr/local/bin/jq" && sudo chmod +x "/usr/local/bin/jq"
          #rclone
          sudo curl -qfsSL "https://bin.ajam.dev/$(uname -m)/rclone" -o "/usr/local/bin/rclone" && sudo chmod +x "/usr/local/bin/rclone"
          #yq
          sudo curl -qfsSL "https://bin.ajam.dev/$(uname -m)/yq" -o "/usr/local/bin/yq" && sudo chmod +x "/usr/local/bin/yq"
          sudo cp "/usr/local/bin/yq" "/usr/bin/yq"
          #Yj
          sudo curl -qfsSL "https://bin.ajam.dev/$(uname -m)/yj" -o "/usr/local/bin/yj" && sudo chmod +x "/usr/local/bin/yj"
          ##Create Output Dir
          mkdir -p "$GITHUB_WORKSPACE/main"
        continue-on-error: true

      - name: Install & Setup ndk-pkg
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          ###Install (Stable) : https://github.com/leleliu008/ndk-pkg?tab=readme-ov-file#install-ndk-pkg-via-curl
          #sudo curl -qfsSL "https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg" -o "/usr/local/bin/ndk-pkg"
          #sudo chmod +x "/usr/local/bin/ndk-pkg"
          ## Install (DEV)
          sudo curl -qfsSL "https://raw.githubusercontent.com/leleliu008/ndk-pkg/dev/ndk-pkg" -o "/usr/local/bin/ndk-pkg"
          sudo chmod +x "/usr/local/bin/ndk-pkg"
          ##Setup
          ndk-pkg setup
          ndk-pkg update
          ndk-pkg sysinfo
          ndk-pkg formula-repo-list
          ndk-pkg formula-repo-sync "official-core"
        continue-on-error: true

      - name: Fetch || Update ndk Package Formulas (JSON)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          ##Generate json
          {
             readarray -t pkgs < <(ndk-pkg ls-available | sort -u)
             for pkg in "${pkgs[@]}"; do
                 ndk-pkg info-available "$pkg" --json 2>/dev/null
             done
          } | jq -s 'sort_by(.pkgname)' > "/tmp/ndk.pkgs.json"
          #Maybe change to this later?
          #ndk-pkg ls-available -v --json | jq -s 'sort_by(.pkgname)' > "/tmp/ndk.pkgs.json"
          ##Post Process
          cat "/tmp/ndk.pkgs.json" > "$GITHUB_WORKSPACE/main/pkgs.json"
        continue-on-error: true

      - name: Fetch || Update ndk Package Formulas (Pretty)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          #Generate yaml
          ndk-pkg ls-available -v --yaml | ansi2txt > "/tmp/ndk.pkgs.txt"
          #Post Process
          cat "/tmp/ndk.pkgs.txt" > "$GITHUB_WORKSPACE/main/ndk.pkgs"
        continue-on-error: true

      - name: Fetch || Update ndk Package Formulas (YAML)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          #Generate yaml
          cat "$GITHUB_WORKSPACE/main/pkgs.json" | yj -jy | tee "/tmp/ndk.pkgs.yaml"
          #Post Process
          cat "/tmp/ndk.pkgs.yaml" > "$GITHUB_WORKSPACE/main/pkgs.yaml"
        continue-on-error: true

      - name: Fetch || Update ndk Package Formulas (README)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          ##Generate Readme
          #This is slow & expensive
          #{
          #   readarray -t pkgs < <(ndk-pkg ls-available | sort -u)
          #   for pkg in "${pkgs[@]}"; do
          #       version=$(ndk-pkg info-available "$pkg" version 2>/dev/null | cut -c 1-100)
          #       description=$(ndk-pkg info-available "$pkg" summary 2>/dev/null | cut -c 1-100)
          #       homepage=$(ndk-pkg info-available "$pkg" web-url 2>/dev/null)
          #       git_url=$(ndk-pkg info-available "$pkg" git-url 2>/dev/null)
          #       echo "| [**$pkg**](https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/$pkg.yml) | $version | $description | $homepage | $git_url |"
          #   done
          #} | tee "/tmp/ndk.pkgs"
          #Parse from json
          {
             readarray -t pkgs < <(jq -r '.[].pkgname' "$GITHUB_WORKSPACE/main/pkgs.json")
             for pkg in "${pkgs[@]}"; do
                 version=$(jq -r --arg pkg "$pkg" '.[] | select(.pkgname == $pkg) | .version' "$GITHUB_WORKSPACE/main/pkgs.json" 2>/dev/null | cut -c 1-100)
                 description=$(jq -r --arg pkg "$pkg" '.[] | select(.pkgname == $pkg) | .summary' "$GITHUB_WORKSPACE/main/pkgs.json" 2>/dev/null | cut -c 1-100)
                 homepage=$(jq -r --arg pkg "$pkg" '.[] | select(.pkgname == $pkg) | .web-url' "$GITHUB_WORKSPACE/main/pkgs.json" 2>/dev/null | cut -c 1-100)
                 git_url=$(jq -r --arg pkg "$pkg" '.[] | select(.pkgname == $pkg) | .git-url' "$GITHUB_WORKSPACE/main/pkgs.json" 2>/dev/null | cut -c 1-100)
                 echo "| [**$pkg**](https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/$pkg.yml) | $version | $description | $homepage | $git_url |"
             done
          } > "/tmp/ndk.pkgs"
          ##Post Process
          #cat "/tmp/ndk.pkgs" > "/tmp/ndk.pkgs.md"
        continue-on-error: true

      - name: Update README.md
        run: |
          #Presets
          set +x ; set +e
          #--------------#        
           cd "$GITHUB_WORKSPACE/main"
           echo -e "" > "$GITHUB_WORKSPACE/main/README.md"
           cat "$GITHUB_WORKSPACE/main/INFO.md" 2>/dev/null >> "$GITHUB_WORKSPACE/main/README.md"
           echo -e "" >> "$GITHUB_WORKSPACE/main/README.md"
           echo '---' >> "$GITHUB_WORKSPACE/main/README.md"
           echo "|Package | Version | Description | Homepage | Git |" >> "$GITHUB_WORKSPACE/main/README.md"
           echo "|--------|---------|-------------|----------|-----|" >> "$GITHUB_WORKSPACE/main/README.md"
           cat "/tmp/ndk.pkgs.md" >> "$GITHUB_WORKSPACE/main/README.md"
           echo -e "" >> "$GITHUB_WORKSPACE/main/README.md"
           echo '---' >> "$GITHUB_WORKSPACE/main/README.md"
        continue-on-error: true

      - name: Sync "$GITHUB_WORKSPACE/main/formula" <-- "(https://github.com/leleliu008/ndk-pkg-formula-repository-official-core)"
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          ##Main
          pushd "$(mktemp -d)" >/dev/null 2>&1 && git clone --filter="blob:none" --quiet "https://github.com/leleliu008/ndk-pkg-formula-repository-official-core" && cd "./ndk-pkg-formula-repository-official-core"
          rm -rf "$GITHUB_WORKSPACE/main/formula" && mv "./formula" "$GITHUB_WORKSPACE/main/"
          popd >/dev/null 2>&1
          ###Dev
          #pushd "$(mktemp -d)" >/dev/null 2>&1 && git clone --branch="dev" --filter="blob:none" --quiet "https://github.com/leleliu008/ndk-pkg-formula-repository-official-core" && cd "./ndk-pkg-formula-repository-official-core"
          #rm -rf "$GITHUB_WORKSPACE/main/formula" && mv "./formula" "$GITHUB_WORKSPACE/main/"
          #popd >/dev/null 2>&1
        continue-on-error: true

      - name: Get DateTime
        run: |
          # Date Time
          NEPALI_TIME=$(TZ='Asia/Kathmandu' date +'%Y-%m-%d (%I:%M:%S %p)')
          echo "NEPALI_TIME=$NEPALI_TIME" >> $GITHUB_ENV
        continue-on-error: true

      - name: Git Pull
        run: |
           cd "$GITHUB_WORKSPACE/main" && git pull origin main
        continue-on-error: true
        
   #Commit & Push
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main
          commit_user_name: Azathothas # defaults to "github-actions[bot]"
          commit_user_email: AjamX101@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "✅ Update ndk-pkg Formulas 📦 <-- ${{ env.NEPALI_TIME }} ⌚"
          #push_options: '--force'